#!/usr/bin/env python3
"""Reconcile /config/allowlist.yaml into iptables/ipset rules and
unbound forward-zones.

Layered for testability:
- Pure parse / generate helpers (Allowlist, build_*): no I/O.
- resolve_all: pure orchestration around an injected resolver.
- apply_ipsets / apply_unbound: side effects, called from main().
"""
from __future__ import annotations

import argparse
import dataclasses
import ipaddress
import json
import logging
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Callable, Iterable

import yaml

log = logging.getLogger("reconcile")


# ---------------------------------------------------------------------
# Parse
# ---------------------------------------------------------------------

@dataclasses.dataclass
class Allowlist:
    exact_domains: list[str]
    wildcard_suffixes: list[str]
    cidrs_v4: list[str]
    cidrs_v6: list[str]
    default_ports: list[int]
    port_overrides: dict[str, list[int]]

    def all_ports(self) -> list[int]:
        seen: set[int] = set(self.default_ports)
        for ports in self.port_overrides.values():
            seen.update(ports)
        return sorted(seen)


class ResolveError(RuntimeError):
    pass


def _split_cidrs(cidrs: Iterable[str]) -> tuple[list[str], list[str]]:
    v4, v6 = [], []
    for c in cidrs:
        (v6 if ":" in c else v4).append(c)
    return v4, v6


def parse_allowlist(path: str | Path) -> Allowlist:
    data = yaml.safe_load(Path(path).read_text())
    domains = data.get("domains") or []
    exact: list[str] = []
    wildcards: list[str] = []
    for d in domains:
        d = str(d)
        if d.startswith("*."):
            wildcards.append(d[2:])
        else:
            exact.append(d)
    v4, v6 = _split_cidrs(data.get("cidrs") or [])
    ports = data.get("ports") or {}
    default_ports = list(ports.get("default") or [443])
    overrides_raw = ports.get("overrides") or []
    overrides: dict[str, list[int]] = {}
    for o in overrides_raw:
        overrides[o["match"]] = list(o["ports"])
    return Allowlist(
        exact_domains=exact,
        wildcard_suffixes=wildcards,
        cidrs_v4=v4,
        cidrs_v6=v6,
        default_ports=default_ports,
        port_overrides=overrides,
    )


# ---------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------

def build_unbound_conf(a: Allowlist, *, upstream: str,
                       upstream_tls: bool) -> str:
    """Emit the unbound include file: default-refuse root, explicit
    `transparent` local-zones for every allowed domain (so the root
    refuse doesn't shadow them), and a `forward-zone` per allowed
    domain pointing at the upstream."""
    port = 853 if upstream_tls else 53
    zones = sorted(set(a.exact_domains + a.wildcard_suffixes))
    lines = [
        "# Generated by reconcile.py — do not edit by hand.",
        "server:",
        '    local-zone: "." refuse',
    ]
    for z in zones:
        name = z.rstrip(".") + "."
        lines.append(f'    local-zone: "{name}" transparent')
    lines.append("")

    for z in zones:
        name = z.rstrip(".") + "."
        lines.append("forward-zone:")
        lines.append(f'    name: "{name}"')
        if upstream_tls:
            lines.append("    forward-tls-upstream: yes")
        lines.append(f"    forward-addr: {upstream}@{port}")
        lines.append("")
    return "\n".join(lines) + "\n"


def build_ipset_members(
    a: Allowlist,
    resolve: Callable[[str, str], list[str]],
) -> dict[str, list[str]]:
    """Return {'v4': [...], 'v6': [...]} of ipset members.

    Wildcards contribute NOTHING — they are DNS-enforced only. The
    resolver is asked only about exact domains.
    """
    v4: set[str] = set(a.cidrs_v4)
    v6: set[str] = set(a.cidrs_v6)
    for d in a.exact_domains:
        for addr in resolve(d, "A"):
            v4.add(addr)
        for addr in resolve(d, "AAAA"):
            v6.add(addr)
    return {"v4": sorted(v4), "v6": sorted(v6)}


# ---------------------------------------------------------------------
# Resolve (pure orchestration over an injected resolver)
# ---------------------------------------------------------------------

@dataclasses.dataclass
class ResolveResult:
    succeeded: dict[str, dict[str, list[str]]]
    failed: dict[str, str]

    def exit_code(self) -> int:
        """0 = all succeeded; 2 = partial success; 1 = total failure.

        Step 5 bootstrap treats 1 as fatal but permits 2 (a single
        flapping upstream shouldn't crash the sidecar). Healthcheck
        in step 9 surfaces 2 as unhealthy."""
        if not self.succeeded:
            return 1
        if self.failed:
            return 2
        return 0


def resolve_all(
    a: Allowlist,
    resolve: Callable[[str, str], list[str]],
    *,
    max_attempts: int = 3,
    backoff_base: float = 1.0,
) -> ResolveResult:
    """Resolve every exact domain's A and AAAA records.

    A domain is `succeeded` iff *at least one rtype* resolved (i.e. we
    have *some* IP to allowlist). A domain is `failed` iff both rtypes
    exhausted their retries. Per-rtype failures on a domain that still
    had the other rtype succeed are logged at WARNING but don't flip
    the domain to failed — some domains are v4-only or v6-only and
    that's legitimate.
    """
    succeeded: dict[str, dict[str, list[str]]] = {}
    failed: dict[str, str] = {}
    for d in a.exact_domains:
        per_type: dict[str, list[str]] = {}
        per_type_errors: dict[str, str] = {}
        for rtype in ("A", "AAAA"):
            for attempt in range(max_attempts):
                try:
                    per_type[rtype] = list(resolve(d, rtype))
                    break
                except ResolveError as e:
                    per_type_errors[rtype] = str(e)
                    if attempt + 1 < max_attempts and backoff_base > 0:
                        time.sleep(backoff_base * (2 ** attempt))
        if per_type:
            succeeded[d] = per_type
            for rtype, err in per_type_errors.items():
                if rtype not in per_type:
                    log.warning(
                        "resolve: %s %s exhausted retries (%s) — "
                        "allowlist missing that rtype's IPs",
                        d, rtype, err,
                    )
        else:
            # Both A and AAAA failed. Surface the A error preferentially.
            failed[d] = per_type_errors.get("A") or \
                per_type_errors.get("AAAA") or "no records"
    return ResolveResult(succeeded=succeeded, failed=failed)


# ---------------------------------------------------------------------
# Real resolver (dig subprocess)
# ---------------------------------------------------------------------

def parse_dig_output(out: str) -> list[str]:
    """Parse `dig +short` output into a list of addresses.

    `dig +short` emits one address per line but also emits comment
    lines (leading `;`) and CNAME chain hostnames as bare labels. We
    reject anything that isn't a valid IPv4 or IPv6 literal via
    `ipaddress`, so a hostname like `foo.bar.net.` — even one with
    digits (`dks7yomi95k2d.cloudfront.net.`) — is dropped cleanly
    instead of being handed to `ipset add` where it would crash the
    reconcile.
    """
    results: list[str] = []
    for raw in out.splitlines():
        line = raw.strip().rstrip(".")
        if not line or line.startswith(";"):
            continue
        try:
            ipaddress.ip_address(line)
        except ValueError:
            continue
        results.append(line)
    return results


def dig_resolver(upstream: str) -> Callable[[str, str], list[str]]:
    def resolve(name: str, rtype: str) -> list[str]:
        try:
            out = subprocess.run(
                ["dig", f"@{upstream}", "+short", "+time=3", "+tries=1",
                 name, rtype],
                check=True, capture_output=True, text=True, timeout=10,
            ).stdout
        except (subprocess.CalledProcessError,
                subprocess.TimeoutExpired) as e:
            raise ResolveError(str(e)) from e
        return parse_dig_output(out)
    return resolve


def stub_resolver(_name: str, _rtype: str) -> list[str]:
    """Used by the dry-run path when RECONCILE_STUB_RESOLVER=1 so the
    test doesn't need DNS access. Returns empty → ipsets are empty,
    unbound conf still exercises the full generate path."""
    return []


# ---------------------------------------------------------------------
# Side effects
# ---------------------------------------------------------------------

def write_unbound_conf(conf: str, path: Path) -> bool:
    """Write `conf` to `path` atomically. Returns True if content
    changed, False if identical. Uses temp-and-rename so a crash
    mid-write cannot leave a truncated config file readable by
    unbound."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == conf:
        return False
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(conf)
    os.replace(tmp, path)  # atomic on POSIX within a filesystem
    return True


def reload_unbound() -> None:
    if shutil.which("unbound-control") is None:
        log.warning("unbound-control not on PATH; skipping reload")
        return
    subprocess.run(["unbound-control", "reload"], check=True)


def _is_bogon(obj) -> bool:
    """Return True for addresses/networks that must never appear in an
    egress allowlist: loopback, private (RFC1918 / ULA), link-local
    (169.254/16 — cloud metadata endpoints live here — and fe80::/10),
    multicast, unspecified (0.0.0.0 / ::), reserved.

    Blocks the class of attack where a compromised upstream resolver
    (or a hostile CNAME) answers an allowlisted name with, e.g.,
    169.254.169.254 and the reconciler then programs that into the
    egress ipset, granting the rogue process access to the cloud
    metadata service or to host-side services on the docker bridge.
    """
    # Deliberately NOT including `is_reserved`: that covers documentation
    # ranges (TEST-NET-1/2/3, 240/4 future-use) which don't route on the
    # public internet and are common in examples/fixtures. Blocking them
    # provides no real egress protection and breaks legitimate test
    # configurations.
    return (
        obj.is_loopback
        or obj.is_private
        or obj.is_link_local
        or obj.is_multicast
        or obj.is_unspecified
    )


def _valid_member(addr: str, v6: bool) -> bool:
    """Accept bare IP or CIDR; reject hostnames, cross-family entries,
    and bogons (see `_is_bogon`). `hash:net` would accept any syntactic
    IP/CIDR, so all policy filtering happens here."""
    try:
        if "/" in addr:
            net = ipaddress.ip_network(addr, strict=False)
            if not isinstance(net,
                (ipaddress.IPv6Network if v6 else ipaddress.IPv4Network)):
                return False
            return not _is_bogon(net)
        ip = ipaddress.ip_address(addr)
        if not isinstance(ip,
            (ipaddress.IPv6Address if v6 else ipaddress.IPv4Address)):
            return False
        return not _is_bogon(ip)
    except ValueError:
        return False


def apply_ipsets(members: dict[str, list[str]]) -> None:
    for family, set_name, kind, is_v6 in (
        ("v4", "allowed_v4", "hash:net family inet", False),
        ("v6", "allowed_v6", "hash:net family inet6", True),
    ):
        tmp = f"{set_name}_tmp"
        subprocess.run(["ipset", "create", "-exist", set_name, *kind.split()],
                       check=True)
        subprocess.run(["ipset", "create", "-exist", tmp, *kind.split()],
                       check=True)
        subprocess.run(["ipset", "flush", tmp], check=True)
        for addr in members[family]:
            if not _valid_member(addr, is_v6):
                log.warning(
                    "SECURITY: dropping %s ipset candidate %r "
                    "(bogon / wrong family / unparseable). A compromised "
                    "or misconfigured upstream resolver may be attempting "
                    "to point an allowlisted name at a sensitive internal "
                    "address (metadata, RFC1918, loopback).",
                    family, addr,
                )
                continue
            subprocess.run(["ipset", "add", "-exist", tmp, addr], check=True)
        subprocess.run(["ipset", "swap", tmp, set_name], check=True)
        subprocess.run(["ipset", "destroy", tmp], check=True)


# ---------------------------------------------------------------------
# main
# ---------------------------------------------------------------------

def _dry_run_payload(a: Allowlist, upstream: str,
                     upstream_tls: bool,
                     resolve: Callable[[str, str], list[str]]) -> dict:
    conf = build_unbound_conf(a, upstream=upstream,
                              upstream_tls=upstream_tls)
    members = build_ipset_members(a, resolve)
    return {
        "unbound_conf": conf,
        "ipset_v4": members["v4"],
        "ipset_v6": members["v6"],
        "ports": {
            "default": a.default_ports,
            "overrides": a.port_overrides,
            "union": a.all_ports(),
        },
        "wildcards": a.wildcard_suffixes,
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--config", default="/config/allowlist.yaml")
    p.add_argument("--upstream",
                   default=os.environ.get("DNS_UPSTREAM", "1.1.1.1"))
    p.add_argument("--upstream-tls", action="store_true",
                   default=os.environ.get("DNS_UPSTREAM_TLS", "0") == "1")
    p.add_argument("--unbound-conf",
                   default="/etc/unbound/unbound.conf.d/allowlist.conf")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s reconcile %(levelname)s %(message)s",
    )

    a = parse_allowlist(args.config)

    if os.environ.get("RECONCILE_STUB_RESOLVER") == "1":
        resolve = stub_resolver
    else:
        resolve = dig_resolver(args.upstream)

    if args.dry_run:
        payload = _dry_run_payload(a, args.upstream, args.upstream_tls,
                                   resolve)
        json.dump(payload, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        return 0

    res = resolve_all(a, resolve)
    for d, err in res.failed.items():
        log.warning("resolve failed for %s: %s", d, err)

    def cached(name: str, rtype: str) -> list[str]:
        return res.succeeded.get(name, {}).get(rtype, [])

    members = build_ipset_members(a, cached)
    apply_ipsets(members)

    conf = build_unbound_conf(a, upstream=args.upstream,
                              upstream_tls=args.upstream_tls)
    changed = write_unbound_conf(conf, Path(args.unbound_conf))
    if changed:
        reload_unbound()

    code = res.exit_code()
    if code == 0:
        log.info("reconcile ok: %d domains resolved, %d v4, %d v6",
                 len(res.succeeded), len(members["v4"]),
                 len(members["v6"]))
    else:
        # Partial (2) or total (1) failure: name the failed domains so
        # an operator watching logs sees exactly which egress is broken.
        level = logging.ERROR if code == 1 else logging.WARNING
        log.log(
            level,
            "reconcile DEGRADED: %d resolved, %d failed [%s], "
            "%d v4, %d v6 (exit=%d)",
            len(res.succeeded), len(res.failed),
            ", ".join(sorted(res.failed)) or "-",
            len(members["v4"]), len(members["v6"]), code,
        )
    return code


if __name__ == "__main__":
    sys.exit(main())
